# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4 , 5, 6, 7, 8, 9])
arr = arr.reshape((2,5))
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
arr1 = np.array([[0, 1, 2, 3, 4],
                [5, 6, 7, 8, 9]])
arr2 = np.ones((2,5))
arr3 = np.vstack((arr1,arr2))
arr3 = arr3.astype('int32')
print(arr3)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
arr4 = np.hstack((arr1,arr2))
arr4 = arr4.astype('int32')
print(arr4)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
arr = arr.flatten()
print(arr)

[0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [5]:
arr5 = np.array([
    [ 0, 1, 2],
    [ 3, 4, 5],
    [ 6, 7, 8],
    [ 9, 10, 11],
    [12, 13, 14]
])
arr5 = np.ravel(arr5)
print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [6]:
arr5.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [7]:
arr6 = np.random.randint(1,25, size = (5,5))
print("Original Array: \n")
print (arr6)
print("\n")
print("Square of Array: \n")
print(arr6 ** 2)

Original Array: 

[[10  9 11 24  1]
 [21 15 17 10 23]
 [10 18 18 16 20]
 [ 9  5 13 14  9]
 [18  7  1  6  5]]


Square of Array: 

[[100  81 121 576   1]
 [441 225 289 100 529]
 [100 324 324 256 400]
 [ 81  25 169 196  81]
 [324  49   1  36  25]]


## Question:8

### Create 5x6 an array and find the mean?

In [8]:
print("Original Array: \n")
print (arr6)
print("\n")
print("Mean of Array: \n")
print(arr6.mean())

Original Array: 

[[10  9 11 24  1]
 [21 15 17 10 23]
 [10 18 18 16 20]
 [ 9  5 13 14  9]
 [18  7  1  6  5]]


Mean of Array: 

12.4


## Question:9

### Find the standard deviation of the previous array in Q8?

In [9]:
print("Original Array: \n")
print (arr6)
print("\n")
print("Standard deviation of Array: \n")
print(np.std(arr6))

Original Array: 

[[10  9 11 24  1]
 [21 15 17 10 23]
 [10 18 18 16 20]
 [ 9  5 13 14  9]
 [18  7  1  6  5]]


Standard deviation of Array: 

6.356099432828281


## Question:10

### Find the median of the previous array in Q8?

In [10]:
print("Original Array: \n")
print (arr6)
print("\n")
print("Median of Array: \n")
print(np.median(arr6))

Original Array: 

[[10  9 11 24  1]
 [21 15 17 10 23]
 [10 18 18 16 20]
 [ 9  5 13 14  9]
 [18  7  1  6  5]]


Median of Array: 

11.0


## Question:11

### Find the transpose of the previous array in Q8?

In [11]:
print("Original Array: \n")
print (arr6)
print("\n")
print("Transpose of Array: \n")
print(np.transpose(arr6))

Original Array: 

[[10  9 11 24  1]
 [21 15 17 10 23]
 [10 18 18 16 20]
 [ 9  5 13 14  9]
 [18  7  1  6  5]]


Transpose of Array: 

[[10 21 10  9 18]
 [ 9 15 18  5  7]
 [11 17 18 13  1]
 [24 10 16 14  6]
 [ 1 23 20  9  5]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [12]:
arr7 = np.random.randint(1,20, size = (4,4))
print("Original Array: \n")
print (arr7)
print("\n")
print("Sum of diagonal elements of Array: \n")
print(np.trace(arr7))

Original Array: 

[[ 8 12 14 14]
 [ 8  3 13 12]
 [18  9 17  3]
 [ 3  3  5  7]]


Sum of diagonal elements of Array: 

35


## Question:13

### Find the determinant of the previous array in Q12?

In [13]:
print("Original Array: \n")
print (arr7)
print("\n")
print("Determinant of Array: \n")
print(np.linalg.det(arr7))

Original Array: 

[[ 8 12 14 14]
 [ 8  3 13 12]
 [18  9 17  3]
 [ 3  3  5  7]]


Determinant of Array: 

2021.9999999999986


## Question:14

### Find the 5th and 95th percentile of an array?

In [14]:
print("Original Array: \n")
print (arr7)
print("\n")
print(f"5th percentile of array: {np.percentile(arr7, 5)}")
print(f"95th percentile of array: {np.percentile(arr7, 95)}")


Original Array: 

[[ 8 12 14 14]
 [ 8  3 13 12]
 [18  9 17  3]
 [ 3  3  5  7]]


5th percentile of array: 3.0
95th percentile of array: 17.25


## Question:15

### How to find if a given array has any null values?

In [15]:
np.isnan(arr7).any()

False